name: tanaman_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/logo/logo.png

flutter:

  uses-material-design: true

  assets:
    - lib/thumbnail/
    - lib/detail/
    - lib/font/Product-Sans-Regular.ttf
    - lib/font/VintageRough-DemoVersion-Regular.otf
    - lib/logo/logo.png

  fonts:
    - family: Product Sans
      fonts:
        - asset: lib/font/Product-Sans-Regular.ttf
    - family: Vintage Rough
      fonts:
        - asset: lib/font/VintageRough-DemoVersion-Regular.otf
